# Dockerfile.testkube
FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y curl gcc libffi-dev libssl-dev libpq-dev git docker.io

# Install Python tools
ENV POETRY_VERSION=1.8.2
RUN pip install "poetry==$POETRY_VERSION"
RUN pip install pytest testcontainers

WORKDIR /data/repo
COPY . .
RUN poetry export --without-hashes --format=requirements.txt > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD ["pytest", "-rP"]
