name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - dns_querier/**
      - run.py
      - pyproject.toml
      - poetry.lock
      - .github/workflows/docker-publish.yml

env:
  IMAGE_NAME: testcontainers-demo-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image tag
        id: extract_tag
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
